s = '''ugorczany@hotmail.com
runte.emanuel@gmail.com
williamson.larue@walker.com
deondre.marquardt@shields.com
kschmitt@yahoo.com
haag.jorge@hotmail.com
gparisian@ernser.com
janice35@zulauf.com
okeefe.mathilde@murray.com
sawayn.ismael@jacobi.com
gislason.emil@hotmail.com
allen20@yahoo.com
gdaugherty@huels.info
dcasper@kulas.com
ladams@altenwerth.com
dbechtelar@gmail.com
josue.keebler@yahoo.com
mckenna35@swift.net
cummings.dasia@hotmail.com
dorris.larkin@tremblay.com
hailee90@gmail.com
hartmann.magnus@davis.com
trace.langosh@yahoo.com
harvey96@gmail.com
manuel.toy@quitzon.com
terrell.gutmann@wolf.com
thompson.kaylah@yahoo.com
jewell.auer@robel.biz
jkihn@stracke.net
rodriguez.elnora@hodkiewicz.biz
trevor99@beatty.com
haley.shyanne@batz.com
griffin62@beier.biz
vschaden@daniel.com
gay31@yahoo.com
willms.alexanne@gmail.com
colt.bauch@hotmail.com
isporer@fisher.com
abernathy.wallace@yahoo.com
qlynch@cruickshank.com
shana.luettgen@yahoo.com
guy.ebert@hotmail.com
nickolas.beatty@yahoo.com
monserrat.hegmann@auer.org
ferdman@hotmail.com
joey.becker@hotmail.com
phyllis.daugherty@cartwright.com
qjohns@gmail.com
irunolfsdottir@schiller.info
kessler.brice@morar.com
mlowe@blanda.com
hane.kraig@yahoo.com
earline.heathcote@hill.com
angelica.streich@hotmail.com
felicia41@hotmail.com
tremblay.loma@runolfsson.com
terrence.boyer@huel.com
dgrimes@gmail.com
delaney74@hotmail.com
wisoky.oleta@gmail.com
pwelch@adams.com
jaron.nolan@hotmail.com
funk.jana@johnston.com
padams@gmail.com
foconnell@brown.com
nboyer@hotmail.com
maribel95@swaniawski.biz
llewellyn58@yahoo.com
gpouros@conroy.org
hills.else@yahoo.com
aschoen@yahoo.com
haag.noelia@witting.info
zdibbert@hahn.net
chloe34@mckenzie.info
wconroy@gmail.com
llubowitz@haley.com
hrutherford@friesen.com
ed.wisozk@gmail.com
robbie77@becker.com
grady.sim@stracke.com
zheathcote@hotmail.com
aurelia.cummerata@schneider.net
rex42@jacobs.org
nico54@yahoo.com
roma48@franecki.com
brakus.max@gutmann.com
flavie.mcclure@blanda.net
herzog.myron@yahoo.com
rogelio67@gmail.com
rosetta94@hotmail.com
verona29@gmail.com
hackett.alden@bartoletti.net
xpowlowski@yahoo.com
nmoen@gmail.com
hershel.streich@hettinger.com
wintheiser.diego@yahoo.com
brown.lew@hotmail.com
stacy36@spencer.net
ben03@yahoo.com
boyer.geovany@gmail.com
'''

s = s.split('\n')

with open('emails.txt', 'w') as f:
    for i in s[:-1]:
        f.write(f'"{i}"\n')