version: "3.8"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Novosibirsk
  
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
